export const USERS_PREFIX = '/users'
export const AUTHENTICATE = USERS_PREFIX + '/authenticate'
export const REGISTER_USER = USERS_PREFIX + "/registerUser"
export const REGISTER_ADMIN = USERS_PREFIX + "/registerAdmin"
export const GET_SELF_DETAILS = USERS_PREFIX + "/getSelfDetails"
export const GET_SELF_ID = USERS_PREFIX + "/getSelfId"
export const DELETE_USER = USERS_PREFIX + "/deleteByEmailAddress"
export const GET_ALL_USERS = USERS_PREFIX + "/getAllUsersDetails"
export const EDIT_USER = USERS_PREFIX + "/edit"
export const GET_USER_DETAILS = USERS_PREFIX + "/getUserDetailsByEmail"
export const GET_USER_ID_BY_EMAIL = USERS_PREFIX + "/getIdByEmail"